#!/bin/busybox sh
. "/irf_utils.sh"
basic_setup

#root=$(find_mnt "1aa7420e-2897-4cc5-b43a-15ec79976b7c")
#mount_this $root "/mnt"
#mount_this /mnt/test.sqfs "/mnt2"

#union_mount "1aa7420e-2897-4cc5-b43a-15ec79976b7c" "test.sqfs" "tmpfs" "/mnt"
#cp "/dev/sr0" "/ttt"
mount_this "/dev/sr0" "/sqfs" "-t squashfs"
#union_mount_vm "/sqfs" "tmpfs" "/mnt"
#
#mount_this "/dev/sr0" "/sqfs" "-t squashfs"
mount_this "none" "/tmpfs" "-t tmpfs"

#Copy on write is important. This is the correct order,
#/bin/unionfs -o cow,allow_other,dirs=/tmpfs=rw:/sqfs=ro /mnt
union /tmpfs /sqfs /mnt

switch /mnt #/bin/sh

#/bin/bash
#prepare_sqfs "1aa7420e-2897-4cc5-b43a-15ec79976b7c" "test.sqfs"
#prepare_tmpfs "tmpfs"
echo "failed"
exec sh

#Defaults
init="/sbin/init"
#root="/dev/vg/root"
#enc_root=/dev/sda1

sleep 2
mdev -s
sleep 2

root=$(blkid | sed -n "/uuid/s/\(\/dev\/sd[a-z][0-9]\).*/\1/p")

cryptsetup luksOpen "${root}" root
#lvmdiskscan

#lvm vgchange -a y

mount /dev/mapper/root /newroot

