#!/bin/busybox sh

#Disable kernel messages from popping onto the screen
echo 0 > /proc/sys/kernel/printk

#Wait for kernel messages to subside.
sleep 2

clear

#Create all the symlinks to /bin/busybox
/bin/busybox --install -s

. "/irf_utils.sh"

mount -t proc none /proc
mount -t sysfs none /sys

check_mounted /proc
check_mounted /sys

#Create device nodes
mknod /dev/tty c 5 0
mdev -s

load_keymap
#exec sh

echo "hello world"

#root=$(find_mnt "1aa7420e-2897-4cc5-b43a-15ec79976b7c")
#mount_this $root "/mnt"
#mount_this /mnt/test.sqfs "/mnt2"

#union_mount "1aa7420e-2897-4cc5-b43a-15ec79976b7c" "test.sqfs" "tmpfs" "/mnt"
#cp "/dev/sr0" "/ttt"
mount_this "/dev/sr0" "/sqfs" "-t squashfs"
#union_mount_vm "/sqfs" "tmpfs" "/mnt"
#
#mount_this "/dev/sr0" "/sqfs" "-t squashfs"
mount_this "none" "/tmpfs" "-t tmpfs"

#Copy on write is important. This is the correct order,
/bin/unionfs -o cow,allow_other,dirs=/tmpfs=rw:/sqfs=ro /mnt

umount /sys /proc
echo "Switching root..."

mkdir -p /mnt/run/ /mnt/dev/ /mnt/sys /mnt/proc /mnt/var/log/
mount -t devtmpfs none /mnt/dev

exec switch_root /mnt /sbin/init
#exec switch_root /mnt /bin/sh

#/bin/bash
#prepare_sqfs "1aa7420e-2897-4cc5-b43a-15ec79976b7c" "test.sqfs"
#prepare_tmpfs "tmpfs"
echo "failed"
exec sh

#Defaults
init="/sbin/init"
#root="/dev/vg/root"
#enc_root=/dev/sda1

sleep 2
mdev -s
sleep 2

root=$(blkid | sed -n "/uuid/s/\(\/dev\/sd[a-z][0-9]\).*/\1/p")

cryptsetup luksOpen "${root}" root
#lvmdiskscan

#lvm vgchange -a y

mount /dev/mapper/root /newroot

#Unmount all other mounts so that the ram used by
#the initramfs can be cleared after switch_root
umount /sys /proc

#Switch to the new root and execute init
if [[ -x "/newroot/${init}" ]] ; then
	exec switch_root /newroot "${init}"
fi

#This will only be run if the above line failed
echo "Failed to switch_root, dropping to a shell"
exec sh

